# Generated by Django 5.1.2 on 2025-02-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoinApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(related_name='tasks', to='JoinApp.subtask'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='feedback',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='todo',
            field=models.BooleanField(),
        ),
        migrations.RemoveField(
            model_name='task',
            name='worker',
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ManyToManyField(related_name='tasks', to='JoinApp.contact'),
        ),
    ]
