# Generated by Django 5.1.2 on 2025-02-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoinApp', '0003_alter_task_prio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='JoinApp.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('Urgent', 'Urgent')], default='medium', max_length=10),
        ),
    ]
