# Generated by Django 5.1.2 on 2025-03-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoinApp', '0006_remove_task_subtasks_task_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(related_name='tasks', to='JoinApp.subtask'),
        ),
    ]
